version: 2
updates:
  # Enable version updates for Go
  - package-ecosystem: "gomod" 
    directory: "/" 
    schedule:
      interval: "weekly"
      
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      
  # Enable version updates for npm (frontend)
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
      
  # Enable version updates for Terraform - dev environment
  - package-ecosystem: "terraform"
    directory: "/terraform/environments/dev"
    schedule:
      interval: "weekly"
      
  # Enable version updates for Terraform - prod environment
  - package-ecosystem: "terraform"
    directory: "/terraform/environments/prod"
    schedule:
      interval: "weekly"
      
  # Enable version updates for Terraform - modules
  - package-ecosystem: "terraform"
    directory: "/terraform/modules"
    schedule:
      interval: "weekly"